### ISSUE TITLE
Crash when creating new world it seems like?

### ISSUE THREAD

**Issue by ExDrill** [Soro335/WilderWild#79]
This happened with the create new world screen, but it's possible it could be affecting more. This is on the 1.19 version.

```
java.lang.IllegalArgumentException: Multiple entries with same key: "fireflies"=[] and "fireflies"=[]
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538)
	at com.mojang.serialization.RecordBuilder$MapBuilder.build(RecordBuilder.java:175)
	at com.mojang.serialization.RecordBuilder$MapBuilder.build(RecordBuilder.java:158)
	at com.mojang.serialization.RecordBuilder$AbstractBuilder.lambda$build$0(RecordBuilder.java:61)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.RecordBuilder$AbstractBuilder.build(RecordBuilder.java:61)
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96)
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14)
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24)
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39)
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:296)
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112)
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$8.encode(RecordCodecBuilder.java:379)
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112)
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96)
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14)
	at net.minecraft.class_5506$class_5507.method_31159(class_5506.java:120)
	at net.minecraft.class_5455.method_31141(class_5455.java:280)
	at net.minecraft.class_5455.method_40314(class_5455.java:266)
	at net.minecraft.class_525.mda2b943$lambda$wt_NewDefaultSettings$0$0(class_525.java:792)
	at net.minecraft.class_7237.method_42098(class_7237.java:24)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_526.method_19944(class_526.java:72)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	```

**Comment by MerpisMe** [comment]
wait what the
are fireflies accidentally registered twice somewhere..?

**Comment by BluePhoenixLOL** [comment]
Are you using any other mods?

**Comment by ExDrill** [comment]
```

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1115867808 bytes (1064 MiB) / 2627731456 bytes (2506 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32696.06
	Virtual memory used (MB): 17273.31
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 174.03
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		architectury: Architectury 5.12.42
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 2.0.20
		cave_enhancements: Cave Enhancements 1.19-FABRIC-1.3.3
		chalk: Chalk 2.1.0+1.19
		charm: Charm 4.2.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chimes: Chimes 1.1.3
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 10.0+3
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		echoplus: Echoplus 0.1.1
		ecologics: Ecologics 2.1.7
		effective: Effective 1.2.2
		enderscape: Enderscape 0.3.4-1.19
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		farmersdelight: Farmer's Delight 1.19-1.3.1
		fireworkfrenzy: Firework Frenzy 1.10
		friendsandfoes: Friends&Foes 1.5.5
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.14_fabric
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		hedgehog: Hedgehog 1.19-1.0.0
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		jamlib: JamLib 0.4.2
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.8.1
		lucys_sloths: Lucy's Sloths 1.0-SNAPSHOT
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		moonlight: Moonlight 1.19-2.0.15
		naturalist: Naturalist 2.1.1
		notenoughanimations: NotEnoughAnimations 1.6.1
		onsoulfire: On Soul Fire 1.19-2
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			midnightlib: MidnightLib 0.5.2
		overweight_farming: Overweight Farming 1.19-1.5.3-fabric
		ratsmischief: Rat's Mischief 1.3.9
		rightclickharvest: Right Click Harvest 3.0.0
		roughlyenoughitems: Roughly Enough Items 9.1.526
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		shinyhorses: Shiny Horses 1.0.0
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		steves_vanilla: Steves Vanilla 1.0.0+1.19
		supplementaries: Supplementaries 1.19-2.0.13
		unvotedandshelved: Unvoted & Shelved 2.0.4
		visuality: Visuality 0.5.1
		wilderwild: Wilder Wild 1.0.0-Fabric+1.19
		wthit: wthit 5.10.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.95, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	```

**Comment by MerpisMe** [comment]
try going down you mod list and removing one mod at a time, restarting your game with each. start with ones you think might be most likely and go down the list

**Comment by ExDrill** [comment]
Alright, this might take a while.

**Comment by ExDrill** [comment]
It was Naturalist, it also adds in fireflies to the game, so it seems like a compatibility issue.

**Comment by MerpisMe** [comment]
> It was Naturalist, it also adds in fireflies to the game, so it seems like a compatibility issue.

alright, we're currently working on fixing this so that the two can coexist with one another. thanks for the report! could you let them know to also change the registry of their fireflies to something like "naturalist_fireflies" to prevent conflicts with other mods that add fireflies?

**Comment by BluePhoenixLOL** [comment]
odd i guess we will rename them to DSRFOIGJDGFSJIOGFD

**Comment by AViewFromTheTop** [comment]
SpawnGroup problem, found and fixed by TreeTrain I believe
