### ISSUE TITLE
Wilder Wild 1.0.3 & 1.0.4 crashes on Quilt

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#88]
This is caused by the datafixer API port failing to check if Quilt is being run, causing it to conflict with the existing datafixer API and crash.

This one's all you @Treetrain1 :trollface: 

`SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Non-unique Mixin config name quilt_datafixerupper.mixins.json used by the mods wilderwild and quilt_datafixerupper
    at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:107)
    at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
    at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70)
    at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    ... 6 more`

**Comment by Treetrain1** [comment]
fixed
